#!/bin/bash
#set -x
log_file=/tmp/dhclient-exit-hooks.log
exec > $log_file 2>&1

exit_hook_dir=${ETCDIR}/exit-hooks.d
if [ -d ${exit_hook_dir} ]; then
    for f in ${exit_hook_dir}/*.sh ; do
        if [ -x ${f} ]; then
            . ${f}
        fi
    done
fi
